### ISSUE TITLE
Problem with Joining

### ISSUE THREAD

**Issue by wpfundstein** [RadioControlli/RC-WLE5-868#1]
Hi,

i have the USB Dongle LORA module STM32WLE5JC and your software flashed.

i get always txTimeOut.

here the output serial:

APPLICATION_VERSION: V1.3.0<\r><\n>
MW_LORAWAN_VERSION:  V2.5.0<\r><\n>
MW_RADIO_VERSION:    V1.3.0<\r><\n>
L2_SPEC_VERSION:     V1.0.4<\r><\n>
RP_SPEC_VERSION:     V2-1.0.1<\r><\n>
###### DevAddr:     05:4A:1A:F6<\r><\n>
0s030:TX on freq 868100000 Hz at DR 0<\r><\n>
4s032:MAC txTimeOut<\r><\n>
<\r><\n>
###### = JOIN FAILED<\r><\n>
10s036:TX on freq 868500000 Hz at DR 0<\r><\n>
14s038:MAC txTimeOut<\r><\n>
<\r><\n>
###### = JOIN FAILED<\r><\n>
20s041:TX on freq 868100000 Hz at DR 0<\r><\n>
24s043:MAC txTimeOut<\r><\n>
<\r><\n>
###### = JOIN FAILED<\r><\n>
30s047:TX on freq 868500000 Hz at DR 0<\r><\n>
34s049:MAC txTimeOut<\r><\n>
<\r><\n>

what happens?

**Comment by weliwang** [comment]
Hi wpfundstein
could you send hex to RadioControlli.
i will verify it.

**Comment by wpfundstein** [comment]
Hi weilang,

i have downloaded the "en.stm32cubewl-v1-3-0\STM32Cube_FW_WL_V1.3.0" example from ST, removed the Buttons and changed the Pin configuration for the led. it works ;-)

Regards, Werner

**Comment by weliwang** [comment]
Hi wpfundstein
Because you are using the TCXO version,
Please make the following modifications.
Please go to .RC-WLE5-868\STM32Cube_FW_WL_V1.3.0\Drivers\BSP\STM32WLxx_Nucleo\stm32wlxx_nucleo_radio.c and change line 235 to RADIO_CONF_TCXO_SUPPORTED


`int32_t BSP_RADIO_IsTCXO(void)
{
return RADIO_CONF_TCXO_SUPPORTED;
}`

**Comment by wpfundstein** [comment]
Hi weilang,

many thanks. now it works.
